### ISSUE TITLE
Doesn't seem to work with the Ultimate IO board in one of the multi-mode modes (specifically Xinput)

### ISSUE THREAD

**Issue by bitpantry** [shaunquick/ipacultimateio#1]
In the ~/ipacultimateio/lib/common/globalvar.py file, the vendor and device ID are hard coded as 0xD209 and 0x0410 respectively. This works fine when the board with the [multi-mode firmware](https://www.ultimarc.com/control-interfaces/i-pacs/i-pac-ultimate-i-o/) is in the standard default (keyboard) mode, but when the board is in the Xinput mode, it shows up as a Microsoft Xbox controller with a vendor and device ID of 0x045e and 0x028e respectively. 

I can update the hardcoded values in the globalvar.py and the ipacultimateio.rules files to be the Xinput IDs, it doesn't work (I get an error about not being able to resolve the device).

Is there anything I can do to get this working when the board is in Xinput mode?

**Comment by shaunquick** [comment]
Hi bitpantry,

having a look at the software SDK https://www.ultimarc.com/programmers-page , looks like the the Product ID for the ipacultimate IO can be in the range of 
#define PID_IPACULTIMATEIO_LO		0x0410	// Start I-Pac Ultimate I/O PID
#define PID_IPACULTIMATEIO_HI		0x0413	// End I-Pac Ultimate I/O PID

This is found in C++/PacDrive.h

So the function "IsValidIpacUltimateDevice" in https://github.com/shaunquick/ipacultimateio/blob/main/lib/common/validations.py
should be looking for Product ID's in that range.

Base on the SDK code, it looks like the Vendor ID should remain as 0xd209.

I have not got a spare board to test the above out on - could you try that ?

**Comment by bitpantry** [comment]
Haven't been able to get this to work yet. Read the docs and some posts about interfacing with xbox controllers with no luck. This is the most python I've written since college and I've never used these libraries before. Seems like the problem is that when the boards are in the Xinput mode, the pi recognizes them as actual xbox controllers - correct vendor and product ids (lsusb). So, in my limited knowledge seems like they are no longer presenting the interfaces / access to control the LEDs. As validation, when in Xinput mode, LED Blinky on my PC complains that it can't find any LED controllers plugged into the computer.

I think I may reach out to ultimarc to see if they con provide some insight - they may have some utilities or know whether or not we're on the right path here.

**Comment by shaunquick** [comment]
https://www.ultimarc.com/control-interfaces/i-pacs/i-pac-ultimate-i-o/

The page does state that 

"Owing to the limitations imposed by the Xinput protocol, the following are NOT supported in Xinput modes but are supported in keyboard and Directinput modes:
Mouse buttons
Volume up and down buttons
Power, sleep, wake buttons
LED control (I-PAC Ultimate I/O only)
No trackball/spinner support

WinIPAC configuration changes take slightly longer in Xinput mode."

So unfortunately the utility will not work in Xinput mode.
