### ISSUE TITLE
Disable Default Ipac LED Animations

### ISSUE THREAD

**Issue by bitpantry** [shaunquick/ipacultimateio#7]
Hi shaunquick - making a lot of progress here getting my 2 board setup working - thanks to your help. 

I'm trying to get LEDs setup for my game systems (e.g., when you load an NES game have it light up just the buttons for NES input). I can run a script and get the buttons to light up, but as soon as the script finishes turning on the right buttons, the default ultimate IO animation script kicks in (where it lights up and turns off random LEDs). I've used the set-ultimateio-leds.py and set-ultimate-rom-leds.py to see if anything different happens - seem to perform the same.

I've attached my script. Do you know how I would run this and have it "stick" once it's done lighting the right LEDs? Thanks 

(had to change extension from json to txt to for github to accept my upload)
[esui.txt](https://github.com/shaunquick/ipacultimateio/files/11526219/esui.txt)

EDIT -----

 It actually may only be the second board that's not behaving (at least tonight - although I'm 90% sure both boards were not working as expected). I've added a link to a video of me running this script. Board 1 controls all LEDs on the left (draw a line down the middle of the board between the the four buttons up top) and Board 2 controls the LEDs on the right.

https://1drv.ms/v/s!Aub7fGtMSkhZipR-7ipKuthT7XQ6ww?e=qGaqag

You can see the LEDs on the left - that's my p1 LEDs in the attached script - seem to "stick" once set. As I'm writing this they are still holding fast. The LEDs on the right board immediately revert back to the default animation on the board.

**Comment by shaunquick** [comment]
Hi there,

So the script looks good - so not sure what is going on. 
The script provided should set all led's across both boards to off and looks like it only sets to buttons on one board ,unless the ledgroupname is set for both boards. Is the script only setting the buttons on the right hand board (as it looks to only set one of the buttons and the script looks to set 4 buttons).

Are the two boards exactly the same ? i.e. are they running the same firmware version ?

The script and code will just set the led's and should not run the default behaviour of the board (i.e. the default script). With my board, once you have setup the led's the default script is not executed (leaving the buttons set as per the script).

To help debug this, you could add a Wait command between turning off all leds before turning the 4 buttons on.
For example
	{ 
		"Command" : {
			"Function" : "Wait",
			"WaitIntervalTime": 5 
		}
	},

it would be interesting to know if the default script kicks in during that wait period.

**Comment by bitpantry** [comment]
Hi shaunquick -

The script is setting 4 buttons on board 1 and one button on board 2 (p2a) - I wanted to light up at least one button on board 2 to see if that was part of the problem. This morning, I rebooted the pi and both boards are behaving incorrectly (unlike last night when board 1 did seem to be working).

Both are running the latest firmware (1.55) but both of my boards are running the multimode versions of the firmware. Also, my second board is running the ID2 version of the firmware so it has a unique ID on the OS. That could be the problem - I can't find the original 1.55 firmware on the website, so I may need to ask Ultimarc if they can send me a link (if it's even possible to roll back). Worth a shot since I don't use the multimode anymore.

I tried the wait command, and it doesn't seem to matter - the default animation runs right over it. I even unplugged one of the boards so I only had a single board setup (my LED group name definitions include a board ID though, so it's not exactly like a single board setup).

Thoughts? Sounds like the big difference is my firmware. I think I'll see if I can go back to the original.

**Comment by shaunquick** [comment]
I'll check my firmware version. I believe it is 1.55 (the out of the box one).

so within the 5 second wait - did the default animation kick in ? 

It might be worthwhile using WinIPAC to remove the default animation (at least I think that you can do that) to check if this helps, on both boards - but yep, would be good to check with ultimarc specifically on this one.

When I tested, I used the board ID and I did not get the behaviour that you see, so I  don't think that will be the root cause.

**Comment by bitpantry** [comment]
Yes - with the 5 sec wait, the default animation still kicked in.

Didn't know you could remove the default animation with the WinIPC tool - I'll have to look at it when I finish with my day-job :)

I have an email out to Ultimarc to see if I can't download the original firmware from somewhere.

**Comment by shaunquick** [comment]
so looking at this page
https://www.ultimarc.com/output/led-and-output-controllers/pacled64/
"When a command is sent by the PC via USB, the script stops running and the command is processed. The script is then not run again until the next power-on."
(I have the standard attract script on my board, but after sending a command it does stop and does not restart until a power off/on action.

I believe that the ultimate IO should work the same - but let's see.

**Comment by bitpantry** [comment]
That's interesting - Are you plugging your boards into a raspberry pi to test? It seems like if I leave it plugged in and alone long enough, the default script eventually stops running and then my commands over the USB "stick". Weird behavior.

I got this back from Ultimarc when asking for the original 1.55 firmware by the way ..

---

1.55 is multimode firmware. 

There is no 1.55 firmware which is not multi-mode. This version is shipped on all boards.

---

I don't think my firmware was the multimode firmware until I explicitly installed it. Can you check the firmware version on yours? Does it say multimode when you use the WinIPAC app?

![image](https://github.com/shaunquick/ipacultimateio/assets/11947587/855aa90f-43e4-40f7-a912-78eb4a876142)

**Comment by bitpantry** [comment]
Update - I asked Ultimarc about what I’m seeing - the default animation not stopping - and this is the response. Does this help?

—-
It should stop when the first control is activated. As for sending LED commands in theory it should also stop.
 
If you are using LEDBlinky this program sends two commands at startup, namely set fade speed to instant and inter-command delay to zero. That should stop the default script.

**Comment by shaunquick** [comment]
I'll answer the last comment first :-)
So a quick test to try would be (but not necessarily in this order)
1. press button 1 on first board - run test - deos the first board go back to the default animation ?
2. press a button on both boards - run test - does either board go back to the default animation ?

That can then help to see if I need to add some additional commands to stop animation kicking in

**Comment by shaunquick** [comment]
WinIpac - looks the same to me...
![image](https://github.com/shaunquick/ipacultimateio/assets/52779646/745a3233-5fef-44cf-ae1e-2b3a9bb252f6)

**Comment by shaunquick** [comment]
on the Ultimarc multimode - yep - that is what it is shipped with - did you upgrade with "Alternative Firmware (Mixed Mode)" as that does not work with Retropie (as stated on the Ultimarc site) - if both boards are 1.55 mixed mode that is a bit strange.

I do indeed test directly with the Retropie with the usb board plugged directly into it.

On the winipac - i note the board attached is uio#2 - is the other board configured the same ?

Are both boards connect via its own USB ?

**Comment by shaunquick** [comment]
Ha Ha !!!

I have replicated the issue !

Leave it with me.......(might be a few days or so)

**Comment by bitpantry** [comment]
Excellent news! Glad you have a lead. Here are the answers to your questions if still needed.

- I'm pretty sure (looking back at my notes from 2017) that my original firmware was 1.48 and that when I started this latest build a few months ago, I installed the 1.55 firmware (not to upgrade, but to get the multimode - I didn't realize I was upgrading)
- I did not install the mixed mode; I saw the same documentation and avoided it
- The tests you asked me to perform above don't change anything in the board's behavior from what I can tell
- Yes, both boards are connected via a dedicated USB (no hubs or anything)
 
One board has the 1.55 firmware installed, the other board has the 1.55 ID2 firmware installed (to increment the ID) and it is listed with a "#2" in WinIPAC and LED Blinky (so yes, that was my second board plugged in in the screen shot above). This is per the documentation on the IPAC Downloads tab ...
 
![image](https://github.com/shaunquick/ipacultimateio/assets/11947587/37974629-71bb-4652-ba66-84087c9f1cd7)

**Comment by bitpantry** [comment]
Quick aside - I've been emailing with Andy at Ultimarc (he's great btw - helpful and fast response times). I told him that once this utility is done it may be the only one out there to support multiboard Ultimate IO LED setups in Linux. If you think it makes sense, it sounds like he'd be willing to help support your efforts and make sure folks know where to find it. Here's his latest response to me.
...
Where is this new utility documented as we would always support developers of utilities, with hardware if needed and we would be interested in mentioning it or hosting it on our site.
...
I sent him a link to this repo and told him I'd pass his message along to you.

**Comment by shaunquick** [comment]
Andy at Ultimarc is indeed super helpful !
He already has a link to the utility from his site - so if he wants to add that multi-board support is available now then absolutely fine by me, once it fully works :-)

Thanks for all the info above.

So I believe I have now fixed the issue - with my setup I let the automated script run until the system goes into attract mode, which has commands that run for a thousand times (or after it stops attract mode, whichever is sooner) - and I did not see that the auto-animation was actually running in parallel, so I never noticed the behaviour.  I have used info provided by Andy to add an extra (internal) command to set "inter-command delay to zero" on initialisation - this seems to have fixed the issue - I have not needed to add the command "set fade speed" to stop the automation, but if that is needed after your testing that won't be an issue to add. It works for at least one board and should work for both, but lets see (fingers crossed).

If you can download the newest version and test that would be great.

Thanks for your patience and debugging help!

**Comment by shaunquick** [comment]
I have also updated the scripts folder and data folder - this has my best guess, for each game, for which controls should be lit up. There will be mistakes (I've not checked every one) but if you wanted to light up just the buttons for a specific game then this might save you some time.....

I have removed the x-input changes - as they will not work at all, based on feedback from ultimarc.

**Comment by bitpantry** [comment]
Hey - sorry for the delayed reply. Work got in the way. Everything seems to be working! Thanks so much - will continue to test and let you know if I find anything.
